### ISSUE TITLE
Multi-File OpenAPI specs?

### ISSUE THREAD

**Issue by mikebronner** [JustSteveKing/laravel-redoc#1]
Hi, thanks for creating this package. Our API is spec'd out using multiple OpenAPI files (Redoc seems to recommend this approach as well). I didn't see a way to configure that in the config, as it doesn't accept folder, but requires pointing to a OpenAPI spec file directly.

Thanks for your help, would love to be able to use your package!

**Comment by JustSteveKing** [comment]
Hey @mikebronner unfortunately I am relying on [this package](https://github.com/Redocly/redoc) which only accepts the one openapi spec from what I can see in the docs.

**Comment by mikebronner** [comment]
Thanks for the fast response @JustSteveKing ! :)

Here is the documentation I was reading from Redoc: https://redoc.ly/docs/resources/multi-file-definitions/

I see now that I misunderstood: they advocate using `$refs`, instead of monolithic specs, but having a single master spec file. Your right. I am reworking our API specs now to be in a single file (still using $refs as we have before). Thanks again for this package!
