### ISSUE TITLE
Config Setting Oddity

### ISSUE THREAD

**Issue by mikebronner** [JustSteveKing/laravel-redoc#4]
For some reason the hostname setting only shows the hostname when set to `false` (boolean), but hides the hostname when set to `"false"` (string) as the comments suggest to use. All other config variables work with stringified booleans, which is very confusing. I just wanted to bring this up as an issue, instead of assuming how you want this fixed.

I'm happy to open a PR to bring the config values more inline with what a Laravel develop might expect, if that is something that would help you out. (For example, all the config values are inverted in their meaning, as in `hostname` should actually be `hideHostname` and be a true boolean, then handle it accordingly in the blade view to meet the redoc requirements. Just a suggestion.)

Thanks! :)

**Comment by JustSteveKing** [comment]
Hey @mikebronner I would welcome a PR for sure!
